---
- block:

   - import_tasks: base.yml

   - import_tasks: repo.yml

   - import_tasks: keepalived.yml  

   - import_tasks: software.yml

   - import_tasks: cluster_init.yml

  when: ansible_distribution_release == 'focal' or ansible_distribution_release == 'jammy'