---
- name: Create /etc/apt/keyrings
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Docker and Kubernetes official GPG key
  ansible.builtin.apt_key:
    url: "{{ item.url }}"
    keyring: "{{ item.keyring }}"
  loop:
  - {url: "https://download.docker.com/linux/ubuntu/gpg", keyring: "/etc/apt/keyrings/docker.gpg"}
  - {url: "https://packages.cloud.google.com/apt/doc/apt-key.gpg", keyring: "/etc/apt/keyrings/kubernetes-archive-keyring.gpg"}

- name: Docker and Kubernetes repo
  ansible.builtin.apt_repository:
    repo: "{{ item.repo }}"
    filename: "{{ item.file }}"
    state: present
  loop:
  - {repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable", file: "docker"}
  - {repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main", file: "kubernetes"}
