---
- name: Restart keepalived
  service:
    name: keepalived
    state: restarted
  listen: "restart keepalived"

- name: Restart containerd
  service:
    name: containerd
    state: restarted
  listen: "restart containerd"

- name: Kube flannel
  shell: cd ~ && kubectl apply -f kube-flannel.yml
  listen: "kube flannel"
  when: inventory_hostname == groups["master"][0]